# Generated by Django 5.2.1 on 2025-11-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='modified_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
