# Generated by Django 5.2.1 on 2025-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todo_created_by_name_todo_modified_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='modification_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
